In [ ]:
#created on: 21.06.25

In [ ]:
#https://www.geeksforgeeks.org/python/python-arrays/

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr)
print(arr * 2)  

# Multi-dimensional array
arr2d = np.array([[1, 2], [3, 4]])
print()
print(arr2d)
print(arr2d * 2)



[1 2 3 4]
[2 4 6 8]

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]
